### ISSUE TITLE
Settings tab won't open (syntax issue?) 

### ISSUE THREAD

**Issue by Opius134** [mclemente/fvtt-chat-tabs#6]
Current environment: 
Foundry Virtual Tabletop: Version 11 Stable, 11.308
Game System: dnd5e, 2.3.1

Bug: when attempting to edit the settings, the configuration window doesn't open and the console spits out a message.

Uncaught TypeError: Cannot read properties of undefined (reading 'role')
    at settings.js:176:39
    at Array.filter (<anonymous>)
    at settings.js:176:6
    at Array.forEach (<anonymous>)
    at TabbedChatTabSettings.init (settings.js:168:26)
    at new TabbedChatTabSettings (settings.js:135:8)
    at MonksSettingsConfig.onClickSubmenuWrapper (colorSetting.js:22:25)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:591:14)
    at 🎁SettingsConfig.prototype._onClickSubmenu#0 (libWrapper-wrapper.js:189:20)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
---------------
This can be bypassed by removing the following lines from Settings.js:

Object.keys(this.tabs[key].permissions.users)
				.filter((id) => game.users.get(id).role !== CONST.USER_ROLES.GAMEMASTER)
				.forEach((id) => {
					this.tabs[key].permissions.users[id] = {
						label: game.users.get(id).name,
						value: this.tabs[key].permissions.users[id] ?? RW_PERMISSIONS.EMPTY,
					};
				});
-------
Unfortunately I'm a not a coder, so I can't offer a proper fix. I'm not sure what problems could occur from running in this state, so I'm not certain if this is big issue or not. Either way, thanks for your time!

**Comment by mclemente** [comment]
That part of the code was trying to read data from a user that was deleted. I'll fix it so it filters out non-existant users.

**Comment by Opius134** [comment]
Uh oh, it seems the patch is producing a new error now. All tabs now produce the same information with no filtering between them. 

Uncaught TypeError: Cannot read properties of undefined (reading 'module')
    at ChatTabSource._canShowMessageByFlags (settings.js:197:33)
    at ChatTabSource.canShowMessage (settings.js:178:9)
    at chat-tabs.js:106:55
    at Array.find (<anonymous>)
    at ChatTab.isMessageVisible (chat-tabs.js:106:31)
    at ChatTab.handle (chat-tabs.js:146:24)
    at chat-tabs.js:344:56
    at Messages.forEach (commons.js:4208:9)
    at Tabs.callback (chat-tabs.js:344:19)
    at Tabs.activate (foundry.js:68806:33)
    at Tabs._onClickNav (foundry.js:68821:40)
_canShowMessageByFlags @ settings.js:197
canShowMessage @ settings.js:178
(anonymous) @ chat-tabs.js:106
isMessageVisible @ chat-tabs.js:106
handle @ chat-tabs.js:146
(anonymous) @ chat-tabs.js:344
forEach @ commons.js:4208
callback @ chat-tabs.js:344
activate @ foundry.js:68806
_onClickNav @ foundry.js:68821

![image](https://github.com/mclemente/fvtt-chat-tabs/assets/100728089/02004c4f-7178-4786-9e76-971d9e28b4a8)

![image](https://github.com/mclemente/fvtt-chat-tabs/assets/100728089/c538499c-df90-4360-b143-2d5b6ebb8cc0)

![image](https://github.com/mclemente/fvtt-chat-tabs/assets/100728089/5950cd1b-b75f-43c2-971e-9fe7c3b5147a)

Tested with the change log module, and again with all other modules disabled. Hope it's nothing major!

**Comment by mclemente** [comment]
Oops, should be fixed now. Sorry about that.
